version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/srv/btracker-web:rw
    working_dir: /srv/btracker-web
    environment:
      - SYMFONY_ENV=${APP_ENV}
      - SYMFONY_SECRET=${APP_SECRET}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
      - AMQP_HOST=${AMQP_HOST}
      - AMQP_PORT=${AMQP_PORT}
      - AMQP_USER=${AMQP_USER}
      - AMQP_PASSWORD=${AMQP_PASSWORD}
      - AMQP_VHOST=${AMQP_VHOST}

  db:
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=${DB_USER}
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "${DB_PORT}:3306"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web:/srv/btracker-web/web:ro
    ports:
      - "8080:80"

  rabbit:
    image: "rabbitmq:3.6-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "${AMQP_USER}"
      RABBITMQ_DEFAULT_PASS: "${AMQP_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "${AMQP_VHOST}"
    ports:
      - "${AMQP_PORT}:5672"
      - "${AMQP_PORT2}:15672"

volumes:
  app-web: {}
  db-data: {}
