old_sound_rabbit_mq:
    connections:
        btracker:
            host:               '%amqp_host%'
            port:               '%amqp_port%'
            user:               '%amqp_user%'
            password:           '%amqp_password%'
            vhost:              ~
            lazy:               true
            connection_timeout: '%amqp_connection_timeout%'
            read_write_timeout: '%amqp_read_write_timeout%'
            keepalive:          false
            heartbeat:          0

    producers:
        event:
            connection:         btracker
            exchange_options:   {name: 'event', type: fanout}

    consumers:
        event:
            connection:         btracker
            exchange_options:   {name: 'event', type: fanout}
            queue_options:      {name: 'event', arguments: {'x-ha-policy': ['S', 'all']}}
            qos_options:        {prefetch_size: 0, prefetch_count: 1, global: false}
            callback:           event_save_consumer
