old_sound_rabbit_mq:
    connections:
        btracker:
            url: '%amqp_url%'

    producers:
        event.save:
            connection:         btracker
            exchange_options:   {name: 'event.save', type: fanout}

    consumers:
        event.save:
            connection:         btracker
            exchange_options:   {name: 'event.save', type: fanout}
            queue_options:      {name: 'event.save', arguments: {'x-ha-policy': ['S', 'all']}}
            qos_options:        {prefetch_size: 0, prefetch_count: 1, global: false}
            callback:           event_save_consumer
