old_sound_rabbit_mq:
    connections:
        cms:
            host:     '%amqp_host%'
            port:     '%amqp_port%'
            user:     '%amqp_user%'
            password: '%amqp_password%'
            vhost:    ~
            lazy:     true
            connection_timeout: '%amqp_connection_timeout%'
            read_write_timeout: '%amqp_read_write_timeout%'
            keepalive: false
            heartbeat: 0
