services:
    event_save_consumer:
        class: AppBundle\Consumer\EventSaveConsumer
        calls:
            - [ setEventSaveService, [ "@event_save_service" ] ]

    event_save_service:
        class: AppBundle\Service\EventSaveService
        calls:
            - [ setDoctrine, [ "@doctrine" ] ]
            - [ setLogger, [ "@logger" ] ]
