services:
    # serializer encoders
    json_encoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    # serializer normalizers
    event_normalizer:
        class: AppBundle\Serializer\Normalizer\EventNormalizer

    beacon_normalizer:
        class: AppBundle\Serializer\Normalizer\BeaconNormalizer

    array_normalizer:
        class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer

    # serializers
    event_serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments: [ [ "@event_normalizer", "@beacon_normalizer", "@array_normalizer" ], [ "@json_encoder" ] ]

    rabbitmq_publisher:
        class: AppBundle\Service\RabbitMqPublisher
        calls:
            - [ setEncoder, [ "@json_encoder" ] ]

    event_save_consumer:
        class: AppBundle\Consumer\EventSaveConsumer
        calls:
            - [ setEventSaveService, [ "@event_save_service" ] ]
            - [ setSerializer, [ "@event_serializer" ] ]
            - [ setLogger, [ "@logger" ] ]

    event_save_service:
        class: AppBundle\Service\EventSaveService
        calls:
            - [ setDoctrine, [ "@doctrine" ] ]
            - [ setLogger, [ "@logger" ] ]
            - [ setLocalizationFactory, [ "@app_localization_factory" ] ]

    app_localization_abstract:
        class: AppBundle\Service\Localization\AbstractLocalizationService

    app_localization_mono:
        class: AppBundle\Service\Localization\MonoLocalization

    app_localization_dual:
        class: AppBundle\Service\Localization\DualLocalization

    app_localization_triple:
        class: AppBundle\Service\Localization\TripleLocalization

    app_localization_factory:
        class: AppBundle\Service\Localization\LocalizationFactory
        calls:
            - [ addLocalization, [ "@app_localization_mono" ] ]
            - [ addLocalization, [ "@app_localization_dual" ] ]
            - [ addLocalization, [ "@app_localization_triple" ] ]
